## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved
##
### SPDX-License-Identifier: MIT-0

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.cluster_certificate_authority_data
}

output "cluster_oidc_issuer_url" {
  description = "OIDC issuer Url as generated by the module."
  value       = module.eks.cluster_oidc_issuer_url
}

output "cluster_oidc_provider_arn" {
  description = "OIDC issuer Url as generated by the module."
  value       = module.eks.oidc_provider_arn
}

output "stepfunctions_invoke_cli" {
  description = "Invoke CLI command for StepFunctions to start the EKS Job"
  value       = "aws stepfunctions start-execution --state-machine-arn ${aws_sfn_state_machine.eks_stepfunction_state_machine.arn}"
}
